### ISSUE TITLE
Any plan to update to 2.003?

### ISSUE THREAD

**Issue by NightFurySL2001** [redchenjs/source-han-sans-classic#1]
Thank you for your contribution.

There is a new update to Source Han Sans to a Variable font version. Do you have any plan to update to v2.003?

If not, are you able to share the mapping file to ease further checking?

Thank you.

**Comment by NightFurySL2001** [comment]
您好。

目前思源黑体已更新v2.003版，不知您是否有计划更新至v2.003？

若无计划，不知您是否可以提供您的映射文件 (mapping file) 方便后续人员查阅使用呢？

先此致谢。

**Comment by redchenjs** [comment]
@NightFurySL2001 这个字体是用Source Han Sans K改的，只是用FontCreator加入了几个中文Language ID，手工修改比较繁琐，暂时不知道有什么批处理的好方法。

**Comment by NightFurySL2001** [comment]
请问有办法知道您修改的字符映射吗？或者还记得大概修改的映射文件即可

**Comment by redchenjs** [comment]
原版Source Han Sans K字体，只改了Language ID，字符映射没做改动

**Comment by NightFurySL2001** [comment]
好的，感谢。
